# .goreleaser.yml
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go run doc-generator/doc-generator.go

builds:
  - id: ocsf-tool
    main: .
    binary: ocsf-tool
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: archive
    format_overrides:
      - goos: windows
        format: zip
    files:
      - licence*
      - README.md
      - ./output/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
      exclude:
        - '^docs:'
        - '^test:'